export const students = [
    {
        name: 'Harry Potter',
        house: 'Gryffindor',
        dateOfBirth: '31-07-1980',
        color: 'red',
        wand: ['wood: holly', 'core: phoenix feather', 'length: 11'],
        image: 'https://hp-api.herokuapp.com/images/harry.jpg',
    },
    {
        name: 'Hermione Granger',
        house: 'Gryffindor',
        dateOfBirth: '19-09-1979',
        color: 'red',
        wand: ['wood: vine', 'core: dragon heartstring', 'length: unknown'],
        image: 'https://hp-api.herokuapp.com/images/hermione.jpeg',
    },
    {
        name: 'Ron Weasley',
        house: 'Gryffindor',
        dateOfBirth: '01-03-1980',
        color: 'red',
        wand: ['wood: willow', 'core: unicorn tail-hair', 'length: 14'],
        image: 'https://hp-api.herokuapp.com/images/ron.jpg',
    },
    {
        name: 'Draco Malfoy',
        house: 'Slytherin',
        dateOfBirth: '05-06-1980',
        color: 'green',
        wand: ['wood: hawthorn', 'core: unicorn tail-hair', 'length: 10'],
        image: 'https://hp-api.herokuapp.com/images/draco.jpg',
    },
    {
        name: 'Cedric Diggory',
        house: 'Hufflepuff',
        dateOfBirth: '',
        color: 'yellow',
        wand: ['wood: ash', 'core: unicorn hair', 'length: 12.25'],
        image: 'https://hp-api.herokuapp.com/images/cedric.png',
    },
    {
        name: 'Cho Chang',
        house: 'Ravenclaw',
        dateOfBirth: '',
        color: undefined,
        wand: ['wood: unknown', 'core: unknown', 'length: unknown'],
        image: 'https://hp-api.herokuapp.com/images/cho.jpg',
    },
    {
        name: 'Neville Longbottom',
        house: 'Gryffindor',
        dateOfBirth: '30-07-1980',
        color: 'red',
        wand: ['wood: cherry', 'core: unicorn tail-hair', 'length: 13'],
        image: 'https://hp-api.herokuapp.com/images/neville.jpg',
    },
    {
        name: 'Luna Lovegood',
        house: 'Ravenclaw',
        dateOfBirth: '13-02-1981',
        color: undefined,
        wand: ['wood: unknown', 'core: unknown', 'length: unknown'],
        image: 'https://hp-api.herokuapp.com/images/luna.jpg',
    },
    {
        name: 'Ginny Weasley',
        house: 'Gryffindor',
        dateOfBirth: '11-08-1981',
        color: 'red',
        wand: ['wood: yew', 'core: unknown', 'length: unknown'],
        image: 'https://hp-api.herokuapp.com/images/ginny.jpg',
    },
    {
        name: 'Vincent Crabbe',
        house: 'Slytherin',
        dateOfBirth: '',
        color: 'green',
        wand: ['wood: unknown', 'core: unknown', 'length: unknown'],
        image: 'https://hp-api.herokuapp.com/images/crabbe.jpg',
    },
    {
        name: 'Gregory Goyle',
        house: 'Slytherin',
        dateOfBirth: '',
        color: 'green',
        wand: ['wood: unknown', 'core: unknown', 'length: unknown'],
        image: 'https://hp-api.herokuapp.com/images/goyle.jpg',
    },
];
